import type { Project, Talent, Match, MatchSuggestion } from "./types"

export const mockProjects: Project[] = [
  {
    id: "1",
    title: "Reactフロントエンド開発",
    description:
      "ECサイトのフロントエンド部分をReact + TypeScriptで開発していただきます。レスポンシブデザイン対応、パフォーマンス最適化も含みます。",
    company: "株式会社テックイノベーション",
    budget: 800000,
    currency: "JPY",
    duration: "3ヶ月",
    location: "東京都渋谷区",
    workStyle: "hybrid",
    status: "active",
    requiredSkills: ["React", "TypeScript", "CSS", "HTML"],
    preferredSkills: ["Next.js", "Tailwind CSS", "Figma"],
    experienceLevel: "mid",
    startDate: "2024-02-01",
    endDate: "2024-04-30",
    createdAt: "2024-01-15",
    updatedAt: "2024-01-15",
    applicantCount: 12,
    viewCount: 89,
    contactEmail: "hr@techinnovation.co.jp",
    contactPerson: "田中 太郎",
    priority: "high",
    ageRestriction: "貴社社員まで",
    foreignNationalAllowed: false,
    placementCompany: "TalentMatch Pro",
    isExternal: true,
  },
  {
    id: "2",
    title: "バックエンドAPI設計・開発",
    description:
      "Node.js + Express.jsを使用したRESTful APIの設計・開発をお願いします。データベース設計、セキュリティ対策も含みます。",
    company: "デジタルソリューションズ株式会社",
    budget: 1200000,
    currency: "JPY",
    duration: "4ヶ月",
    location: "大阪府大阪市",
    workStyle: "remote",
    status: "active",
    requiredSkills: ["Node.js", "Express.js", "PostgreSQL", "Docker"],
    preferredSkills: ["AWS", "Redis", "GraphQL"],
    experienceLevel: "senior",
    startDate: "2024-02-15",
    endDate: "2024-06-15",
    createdAt: "2024-01-14",
    updatedAt: "2024-01-14",
    applicantCount: 8,
    viewCount: 156,
    contactEmail: "recruit@digitalsolutions.co.jp",
    contactPerson: "佐藤 花子",
    priority: "medium",
    foreignNationalAllowed: true,
    placementCompany: "TalentMatch Pro",
    isExternal: true,
  },
  {
    id: "3",
    title: "モバイルアプリUI/UX改善",
    description:
      "既存のモバイルアプリのUI/UX改善プロジェクトです。ユーザビリティテスト結果を基に、より使いやすいインターフェースを設計・実装します。",
    company: "スタートアップX",
    budget: 600000,
    currency: "JPY",
    duration: "2ヶ月",
    location: "リモート",
    workStyle: "remote",
    status: "active",
    requiredSkills: ["UI/UX Design", "Figma", "React Native", "Flutter"],
    preferredSkills: ["Adobe XD", "Sketch", "Principle"],
    experienceLevel: "mid",
    startDate: "2024-01-20",
    endDate: "2024-03-20",
    createdAt: "2024-01-13",
    updatedAt: "2024-01-13",
    applicantCount: 15,
    viewCount: 203,
    contactEmail: "jobs@startupx.com",
    contactPerson: "山田 次郎",
    priority: "low",
    ageRestriction: "40歳",
    foreignNationalAllowed: true,
    placementCompany: "TalentMatch Pro",
    isExternal: true,
  },
  {
    id: "4",
    title: "データ分析システム構築",
    description:
      "Pythonを使用したデータ分析システムの構築です。機械学習モデルの実装、データパイプラインの構築を含みます。",
    company: "アナリティクス株式会社",
    budget: 1500000,
    currency: "JPY",
    duration: "6ヶ月",
    location: "東京都新宿区",
    workStyle: "onsite",
    status: "draft",
    requiredSkills: ["Python", "Pandas", "NumPy", "Scikit-learn"],
    preferredSkills: ["TensorFlow", "PyTorch", "Apache Spark"],
    experienceLevel: "expert",
    startDate: "2024-03-01",
    endDate: "2024-08-31",
    createdAt: "2024-01-12",
    updatedAt: "2024-01-12",
    applicantCount: 3,
    viewCount: 67,
    contactEmail: "ml@analytics.co.jp",
    contactPerson: "鈴木 美咲",
    priority: "high",
    ageRestriction: "45歳",
    foreignNationalAllowed: false,
    placementCompany: "TalentMatch Pro",
    isExternal: true,
  },
]

export const mockExternalProjects: Project[] = [
  {
    id: "ext-1",
    title: "クラウドシステム運用保守エンジニア募集",
    description: "大規模クラウドシステムの運用保守業務を担当していただきます。",
    company: "株式会社クラウドテック",
    budget: 0,
    currency: "JPY",
    duration: "長期",
    location: "東京都",
    workStyle: "remote",
    status: "active",
    requiredSkills: ["AWS", "Linux", "Docker", "Kubernetes"],
    preferredSkills: ["Terraform", "Ansible"],
    experienceLevel: "mid",
    startDate: "2025/09/08",
    createdAt: "2025/09/08 17:25",
    updatedAt: "2025/09/08 17:25",
    applicantCount: 0,
    viewCount: 0,
    contactEmail: "",
    contactPerson: "",
    priority: "high",
    ageRestriction: "貴社社員まで",
    foreignNationalAllowed: false,
    placementCompany: "TalentMatch Pro",
    isExternal: true,
  },
  {
    id: "ext-2",
    title: "金融新規事業の試験設計サポート",
    description: "金融業界の新規事業における試験設計業務をサポートしていただきます。",
    company: "フィンテック株式会社",
    budget: 370000,
    currency: "JPY",
    duration: "3ヶ月",
    location: "東京都",
    workStyle: "onsite",
    status: "active",
    requiredSkills: ["テスター", "デバッガー"],
    preferredSkills: [],
    experienceLevel: "junior",
    startDate: "2025/09/08",
    createdAt: "2025/09/08 17:22",
    updatedAt: "2025/09/08 17:22",
    applicantCount: 0,
    viewCount: 0,
    contactEmail: "",
    contactPerson: "",
    priority: "medium",
    foreignNationalAllowed: false,
    placementCompany: "TalentMatch Pro",
    isExternal: true,
  },
  {
    id: "ext-3",
    title: "SQL+Python必須のBIチームメンバー募集",
    description: "ビジネスインテリジェンスチームでのデータ分析業務を担当していただきます。",
    company: "データアナリティクス株式会社",
    budget: 0,
    currency: "JPY",
    duration: "長期",
    location: "東京都",
    workStyle: "remote",
    status: "active",
    requiredSkills: ["Python", "SQL", "データサイエンティスト"],
    preferredSkills: ["QuickSight"],
    experienceLevel: "mid",
    startDate: "2025/09/08",
    createdAt: "2025/09/08 17:15",
    updatedAt: "2025/09/08 17:15",
    applicantCount: 0,
    viewCount: 0,
    contactEmail: "",
    contactPerson: "",
    priority: "high",
    ageRestriction: "49歳",
    foreignNationalAllowed: true,
    placementCompany: "TalentMatch Pro",
    isExternal: true,
  },
]

export const mockTalents: Talent[] = [
  {
    id: "1",
    name: "田中 太郎",
    email: "tanaka@example.com",
    phone: "090-1234-5678",
    title: "フロントエンドエンジニア",
    experience: 5,
    skills: ["React", "TypeScript", "Next.js", "Tailwind CSS", "JavaScript", "HTML", "CSS"],
    hourlyRate: 8000,
    availability: "available",
    location: "東京都",
    workStyle: "hybrid",
    bio: "フロントエンド開発を専門とし、5年の経験があります。特にReactとTypeScriptを得意としており、ユーザビリティを重視したUI/UX設計が可能です。最新の技術トレンドにも敏感で、継続的な学習を心がけています。",
    portfolio: "https://tanaka-portfolio.com",
    createdAt: "2024-01-01",
    updatedAt: "2024-01-15",
  },
  {
    id: "2",
    name: "佐藤 花子",
    email: "sato@example.com",
    phone: "090-2345-6789",
    title: "バックエンドエンジニア",
    experience: 7,
    skills: ["Node.js", "Python", "PostgreSQL", "AWS", "Docker", "Kubernetes", "GraphQL"],
    hourlyRate: 10000,
    availability: "busy",
    location: "大阪府",
    workStyle: "remote",
    bio: "バックエンド開発とクラウドインフラを専門としています。スケーラブルなシステム設計が得意で、マイクロサービスアーキテクチャの構築経験も豊富です。",
    portfolio: "https://sato-dev.com",
    createdAt: "2024-01-02",
    updatedAt: "2024-01-14",
  },
  {
    id: "3",
    name: "山田 次郎",
    email: "yamada@example.com",
    phone: "090-3456-7890",
    title: "フルスタックエンジニア",
    experience: 6,
    skills: ["React", "Node.js", "MongoDB", "Express.js", "Vue.js", "Firebase"],
    hourlyRate: 9000,
    availability: "available",
    location: "福岡県",
    workStyle: "remote",
    bio: "フロントエンドからバックエンドまで幅広く対応可能なフルスタックエンジニアです。スタートアップでの開発経験が豊富で、迅速な開発が得意です。",
    portfolio: "https://yamada-fullstack.dev",
    createdAt: "2024-01-03",
    updatedAt: "2024-01-13",
  },
  {
    id: "4",
    name: "鈴木 美咲",
    email: "suzuki@example.com",
    phone: "090-4567-8901",
    title: "データサイエンティスト",
    experience: 4,
    skills: ["Python", "Pandas", "NumPy", "Scikit-learn", "TensorFlow", "SQL", "Tableau"],
    hourlyRate: 11000,
    availability: "available",
    location: "東京都",
    workStyle: "hybrid",
    bio: "データ分析と機械学習を専門としています。ビジネス課題を数値で解決することに情熱を持っており、分かりやすいデータ可視化も得意です。",
    portfolio: "https://suzuki-datascience.com",
    createdAt: "2024-01-04",
    updatedAt: "2024-01-12",
  },
  {
    id: "5",
    name: "高橋 健太",
    email: "takahashi@example.com",
    phone: "090-5678-9012",
    title: "UI/UXデザイナー",
    experience: 3,
    skills: ["Figma", "Adobe XD", "Sketch", "Principle", "HTML", "CSS", "JavaScript"],
    hourlyRate: 7000,
    availability: "unavailable",
    location: "神奈川県",
    workStyle: "hybrid",
    bio: "ユーザー中心設計を重視したUI/UXデザインを行います。プロトタイピングからユーザビリティテストまで、デザインプロセス全体をカバーできます。",
    portfolio: "https://takahashi-design.portfolio",
    createdAt: "2024-01-05",
    updatedAt: "2024-01-11",
  },
  {
    id: "6",
    name: "伊藤 麻衣",
    email: "ito@example.com",
    phone: "090-6789-0123",
    title: "モバイルアプリ開発者",
    experience: 4,
    skills: ["React Native", "Flutter", "Swift", "Kotlin", "Firebase", "Redux"],
    hourlyRate: 8500,
    availability: "available",
    location: "愛知県",
    workStyle: "remote",
    bio: "iOS・Androidアプリの開発を専門としています。クロスプラットフォーム開発からネイティブ開発まで幅広く対応可能です。",
    portfolio: "https://ito-mobile.dev",
    createdAt: "2024-01-06",
    updatedAt: "2024-01-10",
  },
]

export const mockExternalTalents: Talent[] = [
  {
    id: "ext-t1",
    name: "Johnson Smith",
    email: "johnson@external.com",
    phone: "090-1111-2222",
    title: "シニアReactエンジニア",
    experience: 8,
    skills: ["React", "TypeScript", "Next.js", "GraphQL", "AWS"],
    hourlyRate: 12000,
    availability: "available",
    location: "東京都",
    workStyle: "remote",
    bio: "8年のReact開発経験を持つシニアエンジニア。大規模なWebアプリケーションの設計・開発が得意です。",
    portfolio: "https://johnsonsmith.dev",
    createdAt: "2024-01-01",
    updatedAt: "2024-01-15",
    company: "グローバルテック株式会社",
    foreignNational: true,
    placementCompany: "TechTalent Pro",
    isExternal: true,
  },
  {
    id: "ext-t2",
    name: "李 美花",
    email: "li@external.com",
    phone: "090-2222-3333",
    title: "データサイエンティスト",
    experience: 6,
    skills: ["Python", "Machine Learning", "TensorFlow", "SQL", "Tableau"],
    hourlyRate: 11500,
    availability: "available",
    location: "大阪府",
    workStyle: "hybrid",
    bio: "機械学習とデータ分析のスペシャリスト。金融業界での分析経験が豊富です。",
    portfolio: "https://li-datascience.com",
    createdAt: "2024-01-02",
    updatedAt: "2024-01-14",
    company: "データソリューションズ株式会社",
    foreignNational: true,
    placementCompany: "DataTalent Agency",
    isExternal: true,
  },
  {
    id: "ext-t3",
    name: "田村 健一",
    email: "tamura@external.com",
    phone: "090-3333-4444",
    title: "DevOpsエンジニア",
    experience: 7,
    skills: ["AWS", "Docker", "Kubernetes", "Terraform", "Jenkins"],
    hourlyRate: 13000,
    availability: "busy",
    location: "東京都",
    workStyle: "onsite",
    bio: "クラウドインフラとCI/CDパイプラインの構築が専門。大規模システムの運用経験が豊富です。",
    portfolio: "https://tamura-devops.com",
    createdAt: "2024-01-03",
    updatedAt: "2024-01-13",
    company: "インフラテック株式会社",
    foreignNational: false,
    placementCompany: "CloudTalent Solutions",
    isExternal: true,
  },
]

export const mockMatches: Match[] = [
  {
    id: "1",
    projectId: "1",
    talentId: "1",
    status: "interview_scheduled",
    matchScore: 92,
    proposedAt: "2024-01-16",
    updatedAt: "2024-01-17",
    notes: "スキルマッチ度が高く、経験も豊富。面談を設定済み。",
    timeline: [
      {
        id: "1",
        type: "proposed",
        title: "マッチング提案",
        description: "AIによる自動マッチング提案が作成されました",
        createdAt: "2024-01-16T09:00:00Z",
        createdBy: "システム",
      },
      {
        id: "2",
        type: "interview_scheduled",
        title: "面談設定",
        description: "2024年1月20日 14:00に面談が設定されました",
        createdAt: "2024-01-17T10:30:00Z",
        createdBy: "田中 太郎",
      },
    ],
  },
  {
    id: "2",
    projectId: "2",
    talentId: "2",
    status: "negotiating",
    matchScore: 88,
    proposedAt: "2024-01-15",
    updatedAt: "2024-01-18",
    notes: "面談完了。条件面で調整中。",
    timeline: [
      {
        id: "3",
        type: "proposed",
        title: "マッチング提案",
        description: "手動マッチング提案が作成されました",
        createdAt: "2024-01-15T11:00:00Z",
        createdBy: "管理者",
      },
      {
        id: "4",
        type: "interview_completed",
        title: "面談完了",
        description: "面談が完了し、双方から前向きな回答を得ました",
        createdAt: "2024-01-18T15:00:00Z",
        createdBy: "佐藤 花子",
      },
    ],
  },
  {
    id: "3",
    projectId: "3",
    talentId: "5",
    status: "contracted",
    matchScore: 85,
    proposedAt: "2024-01-10",
    updatedAt: "2024-01-19",
    notes: "契約締結完了。プロジェクト開始準備中。",
    timeline: [
      {
        id: "5",
        type: "proposed",
        title: "マッチング提案",
        description: "AIによる自動マッチング提案が作成されました",
        createdAt: "2024-01-10T14:00:00Z",
        createdBy: "システム",
      },
      {
        id: "6",
        type: "contract_signed",
        title: "契約締結",
        description: "契約書にサインが完了しました",
        createdAt: "2024-01-19T16:00:00Z",
        createdBy: "高橋 健太",
      },
    ],
  },
]

export const mockMatchSuggestions: MatchSuggestion[] = [
  {
    projectId: "4",
    talentId: "4",
    matchScore: 94,
    reasons: ["必須スキルが100%マッチ", "経験年数が要件を満たしている", "過去の類似プロジェクト経験あり"],
    skillMatches: ["Python", "Pandas", "NumPy", "Scikit-learn"],
    concerns: ["リモート勤務の経験が少ない"],
  },
  {
    projectId: "1",
    talentId: "3",
    matchScore: 87,
    reasons: ["フロントエンド経験が豊富", "React/TypeScriptのスキルマッチ", "リモート勤務対応可能"],
    skillMatches: ["React", "Node.js", "JavaScript"],
    concerns: ["TypeScriptの経験が浅い可能性"],
  },
  {
    projectId: "2",
    talentId: "6",
    matchScore: 82,
    reasons: ["モバイル開発経験あり", "フルスタック対応可能", "スタートアップ経験豊富"],
    skillMatches: ["React Native", "Firebase"],
    concerns: ["バックエンドAPI設計の経験が不明"],
  },
]
